### ISSUE TITLE
Failure to clean up observers on instances

### ISSUE THREAD

**Issue by ehuelsmann** [ap/Class-Observable#1]
Hi @ap,

The [Workflow](jonasbn/perl-workflow) project is running into a problem with Class::Observable as [detailed in bug report #10](https://github.com/jonasbn/perl-workflow/issues/10#issuecomment-765640659).

In short, when the object goes out of scope, it is being discarded, leaving the memory address available for allocation of a new instance. When the instance goes out of scope, Class::Observable doesn't clean up the observers on that instance however. So, when a new instance is allocated on the same address (which happened in Workflow's test suite), the observers of the previous instance magically apply to the new instance.

@jonasbn, I've reported the issue here, based on Chris's redirection to Aristotle.

Regards,

Erik.

**Comment by ap** [comment]
This addressed in 2.000 which is now on CPAN.
